import {afterEach,describe,expect,it} from 'vitest';
import {createService,fallbackPlan} from '../server/domain.js';
import {createLiveBridge} from '../server/live-bridge.js';
import {eventWhen,writeEmail} from '../server/email-copy.js';
import {initialFacts} from '../server/fixtures.js';
import type {Planner,ProjectState} from '../shared/types.js';
import {buildDropboxContent} from '../server/dropbox-sync.js';
const services:Array<ReturnType<typeof createService>>=[];
const bridges:Array<ReturnType<typeof createLiveBridge>>=[];
const status=()=>({mode:'demo' as const,model:'fixture',fallbackModel:'fixture',estimatedSpendUsd:0,spendLimitUsd:6});
function setup(planner:Planner=async input=>fallbackPlan(input),live=false){const bridge=live?createLiveBridge({dbPath:':memory:'}):undefined;if(bridge)bridges.push(bridge);const api=createService({dbPath:':memory:',planner,aiStatus:status,bridge});services.push(api);const id=api.getState().project.id;if(bridge)bridge.configure(id,{emailAccount:'planner@example.net',testRecipient:'planner@example.net'});return {api,id,bridge};}
const email=(s:ProjectState)=>s.proposals.find(p=>p.kind==='email'&&p.status==='pending')!;
afterEach(()=>{services.splice(0).forEach(s=>s.close());bridges.splice(0).forEach(b=>b.close());});
describe('Editable, human-readable email drafts',()=>{
 it('formats the stored wall-clock time without shifting the event day',()=>{expect(eventWhen(initialFacts)).toBe('December 11, 2026 at 6 PM Eastern time');expect(eventWhen({...initialFacts,time:'00:30',timezone:'America/Los_Angeles'})).toBe('December 11, 2026 at 12:30 AM Pacific time');});
 it('keeps a new quote an inquiry, including unknown costs and actual requirements',()=>{const draft=writeEmail('Request a quote from CAVA',{name:'Christmas dinner',facts:{...initialFacts,caterer:'CAVA',dietary:'20 kosher meals'}})!;expect(draft.body).toContain('20 kosher meals');expect(draft.body).toContain('December 11');expect(draft.body).toContain('review the quote before booking');expect(draft.body).not.toContain('America/New_York');expect(draft.body).not.toContain('$24');expect(draft.body).toContain('\n\n');});
 it('does not interpret Shah Halal as a meal requirement',()=>{const result=fallbackPlan({note:'cancel catering from shah halal and contact cava instead',area:'catering',facts:initialFacts,sources:[]});expect(result.patch).toEqual({caterer:'CAVA'});});
 it('approves and queues exactly the edited email, rejecting the old preview token',async()=>{const {api,id,bridge}=setup(undefined,true);api.edit(id,{area:'guests',patch:{attendance:250}});await api.tick();const original=email(api.getState());const state=api.editDraft(id,original.id,{subject:'A quick headcount update',body:'Hi team,\n\nCould you plan for 250 guests?\n\nThanks!',draftToken:original.draftToken!});const edited=state.proposals.find(p=>p.id===original.id)!;expect(edited.approvalToken).not.toBe(original.approvalToken);expect(()=>api.decide(id,edited.id,'approve',original.approvalToken)).toThrow('preview changed');api.decide(id,edited.id,'approve',edited.approvalToken);await api.tick();const job=bridge!.listJobs(id).find(j=>j.payload.proposalId===edited.id)!;expect(job.payload.subject).toBe(edited.subject);expect(job.payload.body).toBe(edited.body);expect(()=>api.editDraft(id,edited.id,{subject:'Changed',body:'Too late',draftToken:edited.draftToken!})).toThrow('no longer an editable');});
 it('rejects concurrent edits and preserves custom copy through refresh',async()=>{const {api,id}=setup();api.edit(id,{area:'guests',patch:{attendance:250}});await api.tick();const original=email(api.getState());api.editDraft(id,original.id,{subject:'My subject',body:'My personal message.',draftToken:original.draftToken!});expect(()=>api.editDraft(id,original.id,{subject:'Other editor',body:'Overwrite',draftToken:original.draftToken!})).toThrow('draft changed');expect(api.refreshReview(id).proposals.find(p=>p.id===original.id)).toMatchObject({subject:'My subject',body:'My personal message.'});});
 it('does not rewrite an approved immutable job during copy refresh',async()=>{const {api,id,bridge}=setup(undefined,true);api.edit(id,{area:'guests',patch:{attendance:250}});await api.tick();const original=email(api.getState());api.decide(id,original.id,'approve',original.approvalToken);await api.tick();const payload=structuredClone(bridge!.listJobs(id)[0].payload);api.refreshReview(id);expect(bridge!.listJobs(id)[0].payload).toEqual(payload);});
});
describe('AI operating plans',()=>{
 const action={kind:'plan' as const,title:'Resequence setup around dinner service',reason:'The presentation and dinner share the same room and equipment.',area:'brief' as const,evidenceIds:['brief','equipment-contract'],subject:null,recipient:null,body:'Before guests arrive: test microphones.\nDuring dinner: keep the presentation area clear.\nAssumption to confirm: access before 6 PM.'};
 it('turns a model-authored operating plan into a reviewable saved document, then restores it on Undo',async()=>{const {api,id}=setup(async()=>({patch:{},summary:'Prepared a service sequence',questions:[],evidenceIds:['brief'],actions:[action]}));const edited=api.edit(id,{area:'brief',patch:{notes:'Move the presentation after dinner.'}});const changeId=edited.activity.find(a=>a.canUndo)!.changeId!;await api.tick();const state=api.getState();const plan=state.proposals.find(p=>p.kind==='plan'&&p.status==='pending')!;expect(plan.body).toBe(action.body);api.decideMany(id,[plan.id],'approve');await api.tick();const saved=api.getState();expect(saved.receipts.find(r=>r.proposalId===plan.id)?.status).toBe('local');expect(buildDropboxContent(saved)).toContain('During dinner: keep the presentation area clear');const undone=api.undo(id,changeId);expect(buildDropboxContent(undone)).not.toContain('During dinner: keep the presentation area clear');expect(undone.receipts.some(r=>r.proposalId===plan.id)).toBe(true);});
 it('reconsiders the whole saved event without changing facts or contacting anyone',async()=>{let received:any;const {api,id}=setup(async input=>{received=input;return {patch:{},summary:'Prepared a plan',questions:[],evidenceIds:['brief'],actions:[action]};});const before=api.getState();api.reconsider(id);await api.tick();const after=api.getState();expect(after.project).toEqual(before.project);expect(after.messages).toEqual(before.messages);expect(received.context.projectName).toBe(before.project.name);expect(received.context.budget).toEqual(before.budget);expect(received.structuredOnly).toBe(true);expect(after.proposals.some(p=>p.kind==='plan'&&p.status==='pending')).toBe(true);});
 it('rechecks an AI draft when an approved staffing decision changed its context mid-run',async()=>{let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve;});let calls=0;const {api,id}=setup(async input=>{calls++;if(calls===1)await gate;return {patch:{},summary:'Prepared',questions:[],evidenceIds:['brief'],actions:[{...action,body:action.body+'\nUse '+input.facts.staffCount+' staff.'}]};});api.edit(id,{area:'guests',patch:{attendance:300}});const inFlight=api.tick();const staff=api.getState().proposals.find(p=>p.kind==='fact'&&p.patch?.staffCount===5)!;api.decide(id,staff.id,'approve');release();await inFlight;expect(api.getState().proposals.filter(p=>p.kind==='plan'&&p.status==='pending')).toHaveLength(0);await api.tick();const plan=api.getState().proposals.find(p=>p.kind==='plan'&&p.status==='pending')!;expect(calls).toBe(2);expect(plan.body).toContain('Use 5 staff.');});
 it('keeps venue contracts intact while current planning records change',async()=>{const {api,id}=setup();const original=api.getState().sources.find(s=>s.id==='venue-garden')!.content;api.edit(id,{area:'venue',patch:{venueCostCents:730000}});await api.tick();const state=api.getState();expect(state.sources.find(s=>s.id==='venue-garden')!.content).toBe(original);expect(state.sources.find(s=>s.id==='record:venue')!.content).toContain('$7,300.00');});
});
