/** Public venue identity and descriptive search context, checked against each linked operator or institution.
 * These entries do not establish availability, rental prices, included AV, or a seated-dinner capacity.
 */
export type CatalogVenue={id:string;name:string;address:string;locality:'Cambridge'|'Boston';sourceUrl:string;website:string;sourceCheckedAt:string;aliases:string[];description:string};
const checkedAt='2026-09-20';
export const VENUE_CATALOG:CatalogVenue[]=[
 {id:'mit-johnson-athletic-center',name:'MIT Johnson Athletic Center — Ice Rink',address:'120 Vassar Street, Cambridge, MA 02139',locality:'Cambridge',sourceUrl:'https://calendar.mit.edu/building_w34',website:'https://calendar.mit.edu/building_w34',sourceCheckedAt:checkedAt,aliases:['johnson ice rink','mit ice rink','ice rink','ice skating','hockey','johnson athletic center','w34'],description:'MIT indoor athletics venue with an ice rink, indoor track, tennis courts and a field used for large events. Suitable to investigate for skating activities or campus gatherings; event access and a dining arrangement need confirmation.'},
 {id:'simoni-skating-rink',name:'Simoni Skating Rink',address:'155 Gore Street, Cambridge, MA 02141',locality:'Cambridge',sourceUrl:'https://fmcicesports.com/rink/cambridge-simoni-skating-arena/',website:'https://fmcicesports.com/rink/cambridge-simoni-skating-arena/',sourceCheckedAt:checkedAt,aliases:['simoni arena','cambridge ice rink','ice rink','ice skating','hockey','private ice rental'],description:'Cambridge public ice arena operated by FMC, with private ice rentals, skating outings, skate rental and a snack bar. A recreation venue for an on-ice group activity; a catered dinner space is not established.'},
 {id:'mit-kresge-auditorium',name:'MIT Kresge Auditorium',address:'48 Massachusetts Avenue, Cambridge, MA 02139',locality:'Cambridge',sourceUrl:'https://calendar.mit.edu/building_w16',website:'https://calendar.mit.edu/building_w16',sourceCheckedAt:checkedAt,aliases:['kresge','mit auditorium','w16','performance hall','theatre','theater'],description:'MIT performance building with a main concert hall, smaller theatre, rehearsal rooms and dressing rooms. Relevant for a presentation, awards ceremony, music or stage performance; not a published banquet layout.'},
 {id:'mit-samberg-conference-center',name:'MIT Samberg Conference Center',address:'50 Memorial Drive, Cambridge, MA 02142',locality:'Cambridge',sourceUrl:'https://sambergconferencecenter.mit.edu/',website:'https://sambergconferencecenter.mit.edu/',sourceCheckedAt:checkedAt,aliases:['samberg','mit conference center','e52','river view','skyline','meeting rooms'],description:'MIT conference and event spaces on the sixth and glass-enclosed seventh floors, overlooking the Charles River and Boston skyline. Meeting and dining arrangements vary by room. The center states access is for MIT community events.'},
 {id:'mit-museum',name:'MIT Museum',address:'314 Main Street, Cambridge, MA 02142',locality:'Cambridge',sourceUrl:'https://officesdirectory.mit.edu/mit-museum',website:'https://mitmuseum.mit.edu/',sourceCheckedAt:checkedAt,aliases:['science museum','technology museum','kendall museum','innovation','exhibitions'],description:'MIT museum in Kendall Square with science, technology and design exhibitions and public programming. An option to investigate for a gathering with a museum setting; private rental eligibility, room layout and catering must be confirmed.'},
 {id:'harvard-art-museums',name:'Harvard Art Museums',address:'32 Quincy Street, Cambridge, MA 02138',locality:'Cambridge',sourceUrl:'https://essroombook.fas.harvard.edu/contacts.php?rm=rm0827',website:'https://harvardartmuseums.org/',sourceCheckedAt:checkedAt,aliases:['harvard museum','art museum','menschel hall','gallery','museum reception'],description:'Harvard art museum venue with a listed event-rental contact and Menschel Hall. Relevant for an art-focused reception or presentation. Confirm the permitted event space, museum access, catering and booking conditions.'},
 {id:'multicultural-arts-center',name:'Multicultural Arts Center',address:'41 Second Street, Cambridge, MA 02141',locality:'Cambridge',sourceUrl:'https://multiculturalartscenter.org/artist-opportunities/',website:'https://multiculturalartscenter.org/',sourceCheckedAt:checkedAt,aliases:['multicultural arts','arts center','theatre','theater','studio','performance','workshop'],description:'East Cambridge arts venue with theater and studio rentals for performances, rehearsals, recordings and workshops. A creative setting for a community or arts gathering. The selected rental program has its own eligibility and service terms.'},
 {id:'kimpton-marlowe-hotel',name:'Kimpton Marlowe Hotel',address:'25 Edwin H. Land Boulevard, Cambridge, MA 02141',locality:'Cambridge',sourceUrl:'https://www.hotelmarlowe.com/pdfs/marlowe-event-space-final.pdf',website:'https://www.hotelmarlowe.com/',sourceCheckedAt:checkedAt,aliases:['marlowe hotel','kimpton','serrano ballroom','muse salon','boardroom','hotel meeting'],description:'Cambridge hotel with the Serrano Ballroom, Muse Salon, Alexis Gallery and Marlowe Boardroom on its published event floor plan. Useful for corporate meetings, a ballroom gathering or smaller breakout sessions.'},
 {id:'royal-sonesta-boston',name:'The Royal Sonesta Boston',address:'40 Edwin Land Boulevard, Cambridge, MA 02142',locality:'Cambridge',sourceUrl:'https://www.sonesta.com/royal-sonesta/ma/cambridge/royal-sonesta-boston',website:'https://www.sonesta.com/royal-sonesta/ma/cambridge/royal-sonesta-boston',sourceCheckedAt:checkedAt,aliases:['royal sonesta','sonesta hotel','riverfront hotel','meeting','conference','hotel event'],description:'Hotel on the Cambridge side of the Charles River with meeting and event spaces, dining and accommodation. An option for a corporate gathering with visiting guests; specific room arrangements and services require a quote.'},
 {id:'cambridge-foundry',name:'The Foundry',address:'101 Rogers Street, Cambridge, MA 02142',locality:'Cambridge',sourceUrl:'https://cambridgefoundry.org/reserve-space',website:'https://www.cambridgefoundry.org/',sourceCheckedAt:checkedAt,aliases:['cambridge foundry','community space','creative workshop','performance','demonstration kitchen','maker space'],description:'Cambridge community creativity facility with reservable spaces, including performance, art and dance studios and a demonstration kitchen. Relevant for workshops or a community-oriented gathering; confirm the room and applicable reservation terms.'},
 {id:'harvard-faculty-club',name:'Harvard Faculty Club',address:'20 Quincy Street, Cambridge, MA 02138',locality:'Cambridge',sourceUrl:'https://www.hfc.harvard.edu/events/faculty-club',website:'https://www.hfc.harvard.edu/',sourceCheckedAt:checkedAt,aliases:['faculty club','harvard dining','garden event','private dinner','indoor outdoor reception'],description:'Harvard Square event venue with indoor rooms, outdoor grounds and a garden, plus an on-site catering team. Relevant for a dinner or reception. Confirm event eligibility, the selected room and dietary arrangements.'},
];
