import type { BudgetLine, ScheduleItem, VendorEngagement } from "@/lib/db/schema";
import type { FactMap } from "./facts";
import { factString, factNumber, factValue } from "./facts";

const usd = (cents: number | null) => (cents === null ? "" : (cents / 100).toFixed(2));

export function renderBudgetCsv(lines: BudgetLine[]): string {
  const rows = ["category,item,quantity,unit_usd,subtotal_usd,status,source"];
  let total = 0;
  let unknown = 0;
  for (const l of lines.filter((x) => x.active)) {
    if (l.subtotalCents === null) unknown++;
    else total += l.subtotalCents + l.taxCents;
    const src = l.provenance.map((p) => p.excerpt ?? p.type).join(" | ").replace(/,/g, ";");
    rows.push([l.category, l.label.replace(/,/g, ";"), l.quantity, usd(l.unitCents), usd(l.subtotalCents), l.commitmentStatus, src].join(","));
  }
  rows.push(`Total,${unknown ? `${unknown} item(s) with unknown cost` : ""},,,${usd(total)},,`);
  return rows.join("\n") + "\n";
}

export function renderScheduleCsv(items: ScheduleItem[]): string {
  const rows = ["time,item"];
  for (const i of [...items].sort((a, b) => a.startLocal.localeCompare(b.startLocal))) rows.push(`${i.startLocal},${i.title.replace(/,/g, ";")}`);
  return rows.join("\n") + "\n";
}

export function renderVendorsMd(engagements: VendorEngagement[], contactsByEngagement: Record<string, { name: string; email: string | null } | undefined>): string {
  const out = ["# Vendors (generated by Ripple)", ""];
  for (const e of engagements) {
    const c = contactsByEngagement[e.id];
    out.push(`## ${e.vendorName} — ${e.service}`);
    out.push(`- Quote: ${e.quoteState}; confirmation: ${e.confirmationState}; cancellation: ${e.cancellationState}`);
    if (e.unitCents !== null && e.quantity !== null) out.push(`- Price: ${e.quantity} × $${usd(e.unitCents)}${e.feeCents ? ` + $${usd(e.feeCents)} fees` : ""}`);
    if (e.depositCents !== null) out.push(`- Deposit: $${usd(e.depositCents)} (${e.depositRefundable === false ? "non-refundable" : e.depositRefundable ? "refundable" : "terms unknown"})`);
    if (e.cancellationTerms) out.push(`- Cancellation terms: ${e.cancellationTerms}`);
    if (c) out.push(`- Contact: ${c.name}${c.email ? ` <${c.email}>` : ""}`);
    out.push("");
  }
  return out.join("\n");
}

export function renderBriefMd(facts: FactMap, overrides: Record<string, unknown> = {}): string {
  const get = (k: string) => (k in overrides ? overrides[k] : facts[k]?.value);
  const str = (k: string) => (get(k) as string | undefined) ?? "Unknown";
  const numv = (k: string) => get(k) as number | undefined;
  const format = get("event.format") === "standing_reception" ? "Standing reception" : "Seated dinner";
  const included = (get("venue.included_av") as string[] | undefined) ?? [];
  return [
    `# ${str("event.name")} (SAMPLE DATA)`,
    "",
    "> All figures, names, and contacts in this folder are fictional sample data for the Ripple demo.",
    "",
    `- Date: ${str("event.date")}`,
    `- Timezone: ${str("event.timezone")}`,
    `- Format: ${format}`,
    `- Expected attendance: ${numv("attendance.expected") ?? "Unknown"} guests`,
    `- Total budget ceiling: USD ${numv("budget.ceiling_cents") !== undefined ? (numv("budget.ceiling_cents")! / 100).toLocaleString("en-US") : "Unknown"}`,
    `- Venue: ${str("venue.name")} — ${str("venue.room")}`,
    `- Address: ${str("venue.address")}`,
    `- Seated capacity: ${numv("venue.seated_capacity") ?? "Unknown"}`,
    `- Included AV: ${included.length ? included.join(", ") : "None"}`,
    `- Catering: ${str("catering.vendor")}`,
    `- Dietary options: ${((get("catering.dietary_options") as string[] | undefined) ?? []).join(", ") || "Unknown"}`,
    `- Dinner service: ${str("schedule.dinner_start")}`,
    "",
  ].join("\n");
}

export function invitationSummary(facts: FactMap): string {
  return factString(facts, "invitation.text") ?? "";
}

export function defaultInvitationText(facts: FactMap, overrides: Record<string, unknown> = {}): string {
  const get = <T>(k: string): T | undefined => (k in overrides ? (overrides[k] as T) : (factValue<T>(facts, k) as T | undefined));
  const name = get<string>("event.name") ?? "our event";
  const date = get<string>("event.date") ?? "TBC";
  const venue = get<string>("venue.name") ?? "venue to be confirmed";
  const address = get<string>("venue.address");
  const doors = get<string>("event.time") ?? "TBC";
  const dinner = get<string>("schedule.dinner_start") ?? "TBC";
  const format = get<string>("event.format") === "standing_reception" ? "standing reception" : "seated dinner";
  const diet = get<string[]>("catering.dietary_options") ?? [];
  const dietText = diet.length ? `${diet.map((d) => d.replace("_", "-")).join(", ")} options available.` : "Menu details to follow.";
  const dateText = formatLongDate(date);
  return `Join us for the ${name} on ${dateText} at ${venue}${address ? ` (${address})` : ""}. Doors ${doors}, ${format} ${dinner}. ${dietText}`;
}

export function formatLongDate(iso: string): string {
  const d = new Date(`${iso}T12:00:00Z`);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "long", year: "numeric", timeZone: "UTC" });
}

export function addMinutes(hhmm: string, delta: number): string {
  const [h, m] = hhmm.split(":").map(Number);
  let total = h * 60 + m + delta;
  total = ((total % 1440) + 1440) % 1440;
  return `${String(Math.floor(total / 60)).padStart(2, "0")}:${String(total % 60).padStart(2, "0")}`;
}

export function attendanceNumber(facts: FactMap): number | undefined {
  return factNumber(facts, "attendance.expected");
}
